### ISSUE TITLE
specs falls

### ISSUE THREAD

**Issue by kompolom** [bem/bem-components#1749]
I clone bem-components, then run `npm run unit`

```
Error: specs: 39 failing
    at /home/jenik/myprojects/bem-components/node_modules/enb-bem-specs/lib/runner.js:168:31
    at Array.<anonymous> (/home/jenik/myprojects/bem-components/node_modules/enb-bem-specs/node_modules/vow/lib/vow.js:711:56)
    at Immediate.callFns [as _onImmediate] (/home/jenik/myprojects/bem-components/node_modules/enb-bem-specs/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

npm ERR! Linux 3.19.0-50-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test-specs"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! bem-components@2.4.0 test-specs: `magic run specs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bem-components@2.4.0 test-specs script 'magic run specs'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bem-components package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     magic run specs
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bem-components
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bem-components
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jenik/myprojects/bem-components/npm-debug.log

npm ERR! Linux 3.19.0-50-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "unit"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE
npm ERR! bem-components@2.4.0 unit: `npm run test-specs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bem-components@2.4.0 unit script 'npm run test-specs'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bem-components package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test-specs
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bem-components
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bem-components
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jenik/myprojects/bem-components/npm-debug.log
```

**Comment by tadatuta** [comment]
The reason is npm@3 and flat dependencies installation: https://github.com/enb-bem/enb-bem-specs/issues/50

Until the issue in `enb-bem-specs` is fixed the only workaround is to use `npm 2`.
