### ISSUE TITLE
pull-github-notify fails when PR is done from external fork

### ISSUE THREAD

**Issue by tadatuta** [bem/bem-components#1777]
@birhoff, will you take a look, please?

```
$ if [ "${TRAVIS_PULL_REQUEST}" != "false" ] && [ "${TEST_SCOPE}" == "specs" ]; then
    node notify.js --clear
  fi

/home/travis/build/bem/bem-components/node_modules/pull-github-notify/node_modules/github/index.js:428
                throw new Error("OAuth2 authentication requires a token or key
                      ^
Error: OAuth2 authentication requires a token or key & secret to be set
    at authenticate (/home/travis/build/bem/bem-components/node_modules/pull-github-notify/node_modules/github/index.js:428:23)
    at Object.module.exports.authenticate (/home/travis/build/bem/bem-components/node_modules/pull-github-notify/lib/github-api.js:11:23)
    at module.exports (/home/travis/build/bem/bem-components/node_modules/pull-github-notify/lib/github-agent.js:18:9)
    at module.exports (/home/travis/build/bem/bem-components/node_modules/pull-github-notify/lib/reporter.js:64:42)
    at Object.<anonymous> (/home/travis/build/bem/bem-components/notify.js:7:45)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
The command "if [ "${TRAVIS_PULL_REQUEST}" != "false" ] && [ "${TEST_SCOPE}" == "specs" ]; then
    node notify.js --clear
  fi
  " failed and exited with 1 during .
```

**Comment by veged** [comment]
No longer relevant: Travis CI, Gemini, and showcase infrastructure were removed in v7. CI is now GitHub Actions, visual testing is Playwright. See [v7 branch](https://github.com/bem/bem-components/tree/v7).
