### ISSUE TITLE
_index.js: build error

### ISSUE THREAD

**Issue by mishanga** [bem/bem-components#271]
``` bash
mishanga@mishanga:~/bem-components > bem make desktop.pages/index/_index.js
14:14:35.959 - info: bem 0.7.4
14:14:36.288 - info: Graph:
== root
 all
   build
     common.blocks*
     desktop.blocks*
     touch.blocks*
     desktop.pages*
       common.blocks*
       desktop.blocks*
       touch.blocks*
     touch-phone.pages*
       common.blocks*
       desktop.blocks*
       touch.blocks*
== root
 sets
   desktop.examples*
   desktop.specs*
   touch-pad.examples*
   touch-pad.specs*
   touch-phone.examples*
   touch-phone.specs*

14:14:36.291 - info: [i] Going to build 'desktop.pages*' [1]
14:14:36.882 - info: [i] Going to build 'desktop.pages/index*' [2]
14:14:36.971 - info: [t] Build total: 1009ms
Error: There is no such id in arch.nodes: desktop.pages/index/_index.js
    at throwError (/home/mishanga/bem-components/node_modules/bem/node_modules/apw/lib/asserts.js:8:11)
    at exports.hasId (/home/mishanga/bem-components/node_modules/bem/node_modules/apw/lib/asserts.js:20:28)
    at /home/mishanga/bem-components/node_modules/bem/node_modules/apw/lib/asserts.js:84:42
    at Array.forEach (native)
    at Object.exports.hasIds (/home/mishanga/bem-components/node_modules/bem/node_modules/apw/lib/asserts.js:84:19)
    at Object.module.exports.INHERIT.createPlan (/home/mishanga/bem-components/node_modules/bem/node_modules/apw/lib/arch.js:425:17)
    at module.exports.INHERIT.process (/home/mishanga/bem-components/node_modules/bem/node_modules/apw/lib/apw.js:34:45)
    at /home/mishanga/bem-components/node_modules/bem/lib/make.js:39:30
    at _fulfilled (/home/mishanga/bem-components/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/home/mishanga/bem-components/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/home/mishanga/bem-components/node_modules/q/q.js:760:13)
    at /home/mishanga/bem-components/node_modules/q/q.js:574:44
    at flush (/home/mishanga/bem-components/node_modules/q/q.js:108:17)
From previous event:
    at Cmd.exports.Cmd.Cmd._do (/home/mishanga/bem-components/node_modules/bem/node_modules/coa/lib/cmd.js:424:14)
    at Cmd.exports.Cmd.Cmd.do (/home/mishanga/bem-components/node_modules/bem/node_modules/coa/lib/cmd.js:471:17)
    at Cmd.exports.Cmd.Cmd.run (/home/mishanga/bem-components/node_modules/bem/node_modules/coa/lib/cmd.js:459:22)
    at Object.<anonymous> (/home/mishanga/bem-components/node_modules/bem/bin/bem:6:23)
    at node.js:902:3
```

**Comment by mishanga** [comment]
Closed by [6ac6434fe04cf](https://github.com/bem/bem-components/commit/6ac6434fe04cfe616b65bf5093f9b3b4b709ffe9)
